name: docker-build-push

on:
  push:
    branches:
      - master
    # paths:
    #   - "src/**"

jobs:
  docker-build-push-deploy:
    runs-on: ubuntu-latest
    env:
      SRC: '.'
      DOCKER_IMAGE: 'spring-music'
      DOCKERHUB_ORG: 'griggheo'
    steps:
      - uses: actions/checkout@v3
      - name: Build JAR 
        run: |
          ./.github/scripts/build-app.sh
      - name: Checkout github-actions Repo
        uses: actions/checkout@v3
        with:
          repository: codepraxis-io/github-actions
          path: github-actions
      - name: Build and Push the Docker Image
        uses: ./github-actions/docker-build-push-action
        with:
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
          image_name: ${{ env.DOCKERHUB_ORG }}/${{ env.DOCKER_IMAGE }}
          context: '${{ env.SRC }}'
          dockerfile_path: '${{ env.SRC }}/Dockerfile'
          build_args: ""

