name: gradle-trivy-buildx-eclipse-temurin-17-jammy

on:
  push:
    branches:
      - master
    # paths:
    #   - "src/**"
  workflow_dispatch:
  
jobs:
  gradle-trivy-buildx:
    runs-on: ubuntu-latest
    uses: codepraxis-io/github-actions/.github/workflows/gradle-trivy-buildx.yml@master
    with:
      image_name: 'griggheo/spring-music'
      image_tag_prefix: temurin
      context: '.'
      dockerfile_path: 'Dockerfile.eclipse-temurin-17-jre-jammy'
      extra_tags: 'eclipse-temurin-17-jre-jammy'
      build_args: ''
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      gh_pat: ${{ secrets.GH_PAT }}

